[package]
name = "wc-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_fs = "1.0.13"
clap = { version = "4.4.7", features = ["derive"] }
predicates = "3.0.4"
